### ISSUE TITLE
TFolder and TTask structure is not supported in HierarchyPainter

### ISSUE THREAD

**Issue by mvala** [linev/jsroot#40]
I create file with TFolder structure and add some histogram in it. I see only root folder and i cannot enter in to it. It is working in TBrowser. Here is file 
http://disk.saske.sk/mvala/RsnOutFolder.root
Can you check?

**Comment by linev** [comment]
Hi Martin,

Most probably, TFolder not yet supported in JSROOT.
It is not much better than TList - when you write TFolder to the file, it streamed as single entity.
If you want to partition your data, you should use TDirectory structures in TFile.

Anyway, I will check that is wrong.

**Comment by mvala** [comment]
I changed to TDirectory and it is fine like that. I have also TTask structure and it is not browsable in jsroot. Is there a way to add own objects as user without touching jsroot core code?

**Comment by linev** [comment]
> Is there a way to add own objects as user without touching jsroot core code?

Yes, but it is not documented (yet).  Entry point is here:
https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.js#L8399-L8432

One should create script, which register draw function for user class,
and draw function should have several methods. Simple example for it is:
https://github.com/linev/jsroot/blob/master/scripts/JSRootPainter.more.js#L618-L641

For object browsing there are special functions, which also can be registered (like for TGeoManager).
And for custom binary I/O (custom streamers) different point, where special functions could be append.

Generally speaking, till now there were no requests and I didn't put effort to cleanup this API and make it public. For TFolder and TTask classes there should be solution in JSROOT. If you have in mind really custom class, which should be supported, we could try to adjust code and made proper documentation.

I put some example in ROOT tutorials, but it is rather for use with THttpServer:

https://github.com/root-mirror/root/blob/master/tutorials/http/httptextlog.C
https://github.com/root-mirror/root/blob/master/tutorials/http/httptextlog.js

**Comment by mvala** [comment]
This is exactly what i wanted. Thanks a lot for such perfect support. I will close it when TFolder will work

**Comment by linev** [comment]
> This is exactly what i wanted

You want better support/documentation for arbitrary user classes, 
or just TFolder and TTask support?

**Comment by mvala** [comment]
User class is more important to me. One of my user class will inherent from TTask, so base TTask is also fine, but i would like to have support/documentation for any user class.

**Comment by linev** [comment]
Here how it looks now:

http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutFolder.root

For the moment it is in dev branch.
After I clarify problem with TTask, I could push same code to master and made 4.4.2 release.

Can you provide me an example file with TTask?

**Comment by mvala** [comment]
http://disk.saske.sk/mvala/RsnOutMgr.root

But it contains my own object which inherent from TTask. Is it ok?
if not, then you can generate one from $ROOTSYS/tutorials/tasks.C

**Comment by linev** [comment]
> But it contains my own object which inherent from TTask. Is it ok?

Yes, I could check how to correctly support it.

**Comment by linev** [comment]
As you proposed, I store tasks from $ROOTSYS/tutorials/tasks.C.
Already there inherited classes are used. 
I need to think how to support them

**Comment by linev** [comment]
Main problem with TTask, that it never used as is - only as user-derived class.
Therefore I need to add support of derived classes into JSROOT anyway.
From your example is clear, that you want to access objects inside your TTask-based classes for drawing or just inspection.

Here a first try. 
I can recognize now that user class derived from TTask and can use it for browsing.
Here structure from ROOT example:

http://jsroot.gsi.de/dev/?file=../files/tasks.root&expand=run;1/event/tracker

Here from your file:

http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutMgr.root&expand=RsnMgr;1/input/1/3/10

Instead of object name (clumsy in your case), one can just use index (starts from 0).
One could inspect objects (also with simple click):

http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutMgr.root&item=RsnMgr;1/input/1/3/10/fInput&opt=inspect

You also can draw histograms directly from your lists:

http://jsroot.gsi.de/dev/?file=http://disk.saske.sk/mvala/RsnOutMgr.root&item=RsnMgr;1/input/1/3/10/fOutput/hSignal

Same link with full item names (no idea if works in all browsers):
http://jsroot.gsi.de/dev/index.htm?nobrowser&file=http://disk.saske.sk/mvala/RsnOutMgr.root&item=RsnMgr/input/ctj[-1.00,-0.90]/norm[1.10,1.15]/fit_2[0.997,1.130]/fOutput/hSignal&opt=

Please try and let me know how it works.

**Comment by mvala** [comment]
It works fine. I like it. Is it possible to follow function Browse. In my example i am showing only fOutput
https://github.com/mvala/alice-rsn-analysis/blob/tm/RsnOut/AliRsnOutTask.cxx#L111

**Comment by mvala** [comment]
But i have to say, that your examples looks perfect, i can see all objects. Perferct

**Comment by linev** [comment]
> Is it possible to follow function Browse. In my example i am showing only fOutput

This would be next step, that one defines user-specific browsing function in the JSROOT.
I need to made some internal cleanup before I can explain you how it can be done.
Otherwise you will need to change code very soon again.

**Comment by mvala** [comment]
Ok. I think we can close this ticket. Thank you very much
